# -*- coding: utf-8 -*-
"""TF-IDF

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JWn2fybaBuxKVSQLixvMJmi8Sl5ioa8d
"""

from sklearn.feature_extraction.text import TfidfVectorizer

# Comment
comment = [
    "Setelah liat search bar ternyata banyak banget dari kalian yang pk pm nya ngeblok bahkan kosong tapi lolos di univ dan jurusan keren-keren, nah kalian nguatin subtes lainnya gimana sih? Latsol latsol nya tuh dari mana? Pls kasi aku info dan doain juga ya biar di  (cont..)",
    "ujian mandiri ini aku bisa lolos nyusul kalian",
    "Aaamiiin. senjataku cuma pbm, libind, & litbing aja, itu aku kebanyakan latsol trs habis itu dikoreksi mana yang masih banyak salahnya, pokonya latsolnya yang banyaaak aja nder. untuk pbm biasanya di ka fauzan, karena dia tuh penjelasannya gampang di pahamin",
    "Semoga lolos sender, kalo aku biasanya sesuai sama mood karna kalo belajar gk mood dan terpaksa gada yang masuk😭 jd sebisa mungkin kalo mau belajar naikin mood dl baru mulai, nah biasanya aku belajar dari vidio vidio yg ada di yt/tt si dan sambil di tulis dan materi dari twitter",
    "semoga lolos sender !! aku kuat di pbm sama litbing sih. pbm aku belajar dari thread kak fauzan (ini hrs bgt dipahamin!!) trs to nya dari mipy, litbing dari to al faiz itu jenis soalnya mirip bgt. trs menurutku ppu jg hrs BGT paham rumus silogisme, modus tollens ponens-",
    "aamiin sender!! aku dulu seringnya bljr lit indo&inggris dibanding PM krn aku dah bnr2 pasrah saking gak dongnya..kalopun dong cm 1/2 soal. Dl nyelesaiin buku intensif GO yg lit indo hbs itu lit inggris, KPU jg tak kerjain tapi yg soal2 gmpng, aku bs garap, & gk begitu rumit.",
    "gue dari h-7 tes udah ga belajar pk pm lagi, ngencengin ppu pbm sama pu",
    "aku ngeblok 7 nomor,pk juga 3 nomor soalnya gacukup waktunya tinggal 10 detik, tapi subtes lain bener bener alhamdulillah lancar🥹🥹kalo kata aku kuatin di subtes lain dulu nder, baru terjun ke pkpm, klo emg kmu kek aku yaa (yg sbnernya gasanggup itung itungan tpi ttp maksa)😁",
    "senjataku cmn di pbm, libind, & litbing aja nder. untuk ppu sbnrnya pas itu rada ragu² jwbnnya karna semua pilihannya ngejebak. aku biasa latsol di apk GO, untuk pbm baca thread ka fauzan krna itu bnr² sngt membantu!!! aku bljr pbm disitu cepet paham ✅✅ anw SEMANGAT NDER",
    "Aamiin semangattt sender, aku tunggu kamu flexing almet 🙌, kemarin aku kuatin dasar matematikanya dimulai dari pelajaran SMP. Sama latsol osn matematika, karna ternyata mirip persis sama utbk. terus sisanya aku pakai to alphastude. menurut aku yang terpenting sii paham dasarnya",
   ]

# Membuat objek TF-IDF vectorizer
vectorizer = TfidfVectorizer()

# Menghitung bobot TF-IDF
tfidf_matrix = vectorizer.fit_transform(comment)

# Mendapatkan nama fitur (kata)
komentar = vectorizer.get_feature_names_out()

# Mencetak bobot TF-IDF untuk setiap comment
for i in range(len(comment)):
    print("Komentar ke", i+1)
    for j in range(len(komentar)):
        feature_name = komentar[j]
        tfidf_weight = tfidf_matrix[i, j]
        print(feature_name, ":", tfidf_weight)
    print()